### ISSUE TITLE
pengaduan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/tema-esensi#10]
halaman pengaduan ketika tutup modal

https://github.com/OpenSID/OpenSID/issues/4933

issue di atas serupa dengan kasus di tema natra

**Comment by andifahruddinakas** [comment]
cek commit https://github.com/OpenSID/tema-natra/commit/fe29b2cd24353b4855b20f70cdf99a09ad13cf2d

**Comment by dikisiswanto** [comment]
sudah diperbaiki di https://github.com/OpenSID/tema-esensi/commit/41fe4e69ab96a3ac8644e6de01cf424ff41b0329
