### ISSUE TITLE
Error Console halaman peta

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/tema-esensi#11]
![image](https://user-images.githubusercontent.com/35319600/158116294-fef446ef-05c3-49f5-b6e3-7b4968555d2b.png)

buka peta pilih wilayah > lihat statistik > mucul error console

**Comment by apidong** [comment]
@agungsugiarto mas biar saya yg ngerjakan ini. saya gak bisa assign.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/tema-esensi/pull/27
