### ISSUE TITLE
Paksa Gambar slider menyesuaikan panjang dan lebar slider.

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/tema-esensi#16]
saat upload gambar dengan ukuran besar akan keluar dari slider. sehingga diharapkan gambar menyesuaikan dengan slider. karena jika gambar dibuat menyesuaikan ukuran slider 760px x 400px maka gambarnya akan pecah walaupun sudah dinaikan resolusinya sampai 1000.

![image](https://user-images.githubusercontent.com/48144047/161602824-3f9e99eb-779e-4a90-9d4d-89c1d2fd433d.png)

**Comment by emanuel-simon** [comment]
kalau di saya, gambar yang ingin ditampilkan di slider, saya sesuaikan dulu gambarnya menjadi 800 x 400 px. 
![2022-04-08_09h19_58](https://user-images.githubusercontent.com/48465803/162344548-eb642b55-cd34-4f21-a2a2-d1d16334362c.png)

**Comment by yogiperdana** [comment]
Mohon lampirkan gambarnya disini pak @ai-skematik

**Comment by vickyrolanda** [comment]
**Apa kekurangan yg ingin diatasi?**
- Terjadi croping terhadap gambar yang diupload jika ukurannya diatas Lebar 880px  &  Tinggi 880px.
- Sehingga untuk gambar - gambar yang ukuran lebih besar dari Lebar 880px  &  Tinggi 880px akan Croping .
- Namun jika kondisi ukuran gambar dengan Lebar 880 atau lebih namun tingginya di bawah 880px Makan gambar tidak akan croping.

**Jelaskan solusi yg diinginkan**
- Sebaiknya logika croping di ubah menjadi Jika ukuran gambar di atas Lebar 880px  & Height >= Lebar 
   - Maka tidak perlu di lakukan croping
- Namun Jika Lebar <! Tinggi Maka boleh di resize

**Cara untuk mereplikasi errornya**
Cara upload gambar buka menu 
 > gallery - > Tambah Album - > Rincian Album -> Tambah Gambar Baru
- upload gambar dengan ukuran 800 x 400 (tidak akan di crop)
![800 x 400](https://user-images.githubusercontent.com/59082428/177192855-e62ab6d8-db85-4e76-b0e2-51fd66676dd7.jpg)

- Upload gambar dengan ukuran diatas 880 & tinggi 880 seperti gamabr dibawah (akan di crop)
![1800 x 947](https://user-images.githubusercontent.com/59082428/177192947-b6b1aef1-d6d6-40b9-9eb4-e3246d36c830.jpg)

**Comment by vickyrolanda** [comment]
Sudah dilakukan perbaikan dan pullrequest mungkin bisa di review mas @yogiperdana

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1173
