### ISSUE TITLE
Sesuaikan Gambar Pada Artikel Menjadi Rata Tengah

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/tema-esensi#17]
Sebelumnya maaf saya kurang paham soal coding.
Tampilan gambar pada artikel secara bawaan tema Esensi adalah rata kiri.
Saya coba ganti di article.php ,class=float-left menjadi float-center tampilan gambarnya menjadi rata tengah dan memenuhi layar, 
![2022-04-08_09h16_47](https://user-images.githubusercontent.com/48465803/162345573-2d5710a2-07f1-49cf-95ed-bd0e18e75916.png)

sehingga tampilan baik di browser laptop maupun di android menjadi lebih bagus. 
![2022-04-08_09h30_24](https://user-images.githubusercontent.com/48465803/162345608-da8b8bba-477c-4fb0-bea0-2dd279cf586a.png)

Sejauh ini saya belum menemukan kendala akibat dari perubahan ini.
dan jika perubahan ini tidak mempengaruhi tampilan tema secara keseluruhan, saran saya agar bisa diterapkan di tema Esensi, supaya pengguna tidak perlu merubah sendiri setiap kali ada update.

**Comment by dikisiswanto** [comment]
Terima kasih, apakah lebih baik gambar utama dibuat ukuran full width?

**Comment by emanuel-simon** [comment]
> Terima kasih, apakah lebih baik gambar utama dibuat ukuran full width?

Menurut saya lebih baik semua gambar dibuat full width

**Comment by dikisiswanto** [comment]
Sudah disesuaikan pada commit https://github.com/OpenSID/tema-esensi/commit/ea3afbf97d3e0008ea343546cb271d9daefd9b96
