### ISSUE TITLE
Peta pada artikel pembangunan tidak muncul

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/tema-esensi#19]
https://berputar.opendesa.id/pembangunan/asdasdasdasd

![image](https://user-images.githubusercontent.com/35319600/163093380-41b83456-4118-4c9c-b792-6a254672dcf1.png)

**Comment by dikisiswanto** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/tema-esensi/commit/ac764dafa0538e86d39245017b15f405bee7be92
