### ISSUE TITLE
halaman IDM tidak terload

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/tema-esensi#20]
https://berputar.opendesa.id/status-idm/2020

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/164792953-6bb722d0-f8f8-472d-b3c7-86cfcf3ee818.png)

**Comment by dikisiswanto** [comment]
Sudah disesuaikan pada commit https://github.com/OpenSID/tema-esensi/commit/869037729be0e8d50b2b218d76eb88c882e60bb7
