### ISSUE TITLE
Lokasi peta pembangunan tidak tampil

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/tema-esensi#21]
Lokasi peta pembangunan tidak tampil pada tampilan web

**Comment by dikisiswanto** [comment]
Duplikat #19 , sudah diperbaiki pada commit https://github.com/OpenSID/tema-esensi/commit/ac764dafa0538e86d39245017b15f405bee7be92

**Comment by yogiperdana** [comment]
Baik issue saya close karena sudah diperbaiki
