### ISSUE TITLE
Samakan Tampilan Grafik APBDES di Artikel Dengan APBDES Footer

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/tema-esensi#22]
Tampilan bar grafik realisasi APBDes pada artikel menjadi terbalik, dan persentasenya malah tampil di ujung kanan halaman,
![2022-05-18_09h52_33](https://user-images.githubusercontent.com/48465803/168941806-e109c249-07e4-40ba-a3e5-f815e2e900e7.png)

Sebaiknya disamakan saja dengan APBDES Footer
![2022-05-18_09h51_07](https://user-images.githubusercontent.com/48465803/168941881-84a065b0-ae4b-46b8-b666-7b61fe514260.png)

Issue ini akan dibahas di [Forum ](https://forum.opendesa.id/d/171-tema-esensi-samakan-tampilan-grafik-apbdes-di-artikel-dengan-apbdes-footer)

**Comment by dikisiswanto** [comment]
Sudah diperbaiki pada commit https://github.com/OpenSID/tema-esensi/commit/b2e70638799f29543382a30b64e747b1f2cba8ad
