### ISSUE TITLE
Bug/error: ubah external link css dan js ke local file css js tema esensi

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/tema-esensi#30]
### Jelaskan error yg dialami

saat pengguna tidak ada koneksi internet maka hanya menampilkan loading saja, maka perlu external link css dan js di ubah ke memanggil link local css dan js

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

### Tema Yang Digunakan

esensi

**Comment by dikisiswanto** [comment]
Library AlphineJS yang digunakan di tema esensi menggunakan url dari CDN. Saat ini belum bisa dipanggil dengan metode local file tanpa diinstall sebagai module javascript.

Selain itu jika tetap ingin dijalankan secara offline, font yang digunakan juga perlu didownload dan diatur ulang.
