### ISSUE TITLE
[PREMIUM-22.02 BETA02] Susunan Kolom Widget Tema Esensi Agak Kurang Lebar

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/tema-esensi#6]
### Jelaskan error yg dialami

Susunan Kolom Widget Tema Esensi Agak Kurang Lebar, sehingga menyebabkan beberapa susuan Kolom Widget terkesan tidak muat dan muatan widgetnya turun mengikuti baris dibawahnya

### Cara untuk mereplikasi errornya

Buka Website-->Perhatikan Susunan widget---> Widget "INFO MEDIA SOSIAL",  Widget "GALERI FOTO" dan lainnya

### Hasil yg diharapkan

Suapaya dapat disesuaikan sehingga tampil website lebih menarik

### Tangkapan layar dan log error

TAMPILAN WIDGET "INFO MEDIA SOSIAL" LEBIH MENARIK SEPERTI PETUNJUK TANDA PANAH" SEHINGGA DAPAT MENGHEMAT RUANG KOLOM DIBAWAHNYA UNTUK WEDGET YG LAIN;

![image](https://user-images.githubusercontent.com/64481641/154346554-1f40f83a-acf1-458f-9d80-149a2462f1bf.png)

BENTUK TAMPILAN WIDGET GALERI FOTO--> HARUSNYA BISA DISUSUN UNTUK MUAT 2 KOLOM BARISAN FOTO
![image](https://user-images.githubusercontent.com/64481641/154346712-d01958a0-5551-4199-9320-87d6eb3a4559.png)

Ruang Artikel Yang Kosong Setelah Setting [PAGING]  terlalu jarak Jeda dengan Footer Tempat Tampilan APBDES

![image](https://user-images.githubusercontent.com/64481641/154348691-ec6fb871-bca3-452f-a193-b8300f25b3d2.png)

Tampilan Widget "Aparatur Desa" Terlalu Panjang Ke Bawah

![image](https://user-images.githubusercontent.com/64481641/154351675-f6d0b7fa-3306-4c01-9a1c-6b63c58cf449.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-beta02)

### Tema Yang Digunakan

ESENSI

### Informasi tambahan

https://www.teupinbeulangan.desa.id/

**Comment by dikisiswanto** [comment]
Sudah diperbaiki di branch `main`. Issue saya tutup
