### ISSUE TITLE
slider kekiri mengalami bug

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/tema-esensi#8]
![WhatsApp Image 2022-02-23 at 08 21 1212](https://user-images.githubusercontent.com/35319600/155248840-35c7de52-2d16-4c80-b2c8-1e18a12e32b7.jpg)

**Comment by dikisiswanto** [comment]
Bug apa bung @balongbesuk ?

**Comment by balongbesuk** [comment]
kl tombol kiri d tekan > gambar lari ke kiri kalau tombol kanan d tekan gambar lari ke kiri

apa tombol kanannya yang salah?

**Comment by dikisiswanto** [comment]
solusi yang diambil: mengganti animasi dengan fadeIn dan fadeOut
